root: true

extends: r1cebank

rules:

  no-return-assign: off
  arrow-body-style: off
  array-callback-return: off
  dot-notation: warn
  indent:
    - error
    - 4
    -
      SwitchCase: 1

envs:
  node: true
  commonjs: true
  browser: false
